### ISSUE TITLE
Add "updateable" association to the programmable software components

### ISSUE THREAD

**Issue by apuli1** [openbmc/phosphor-psu-code-mgmt#2]
This issue is raised to add the "updateable" association to the programmable software components in accordance with https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/28894/. 

Here is example code changes, which is done for phosphor-bmc-code-mgmt.
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-bmc-code-mgmt/+/28838/

**Comment by williamspatrick** [comment]
@mine260309 - the bmcweb code for this was merged so we should attempt to make this change fairly quickly.

**Comment by mine260309** [comment]
@williamspatrick Will do it quickly.

**Comment by mine260309** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-psu-code-mgmt/+/30455
